---

- name: "Install zabbix agent"
  hosts: all

  roles:
    - role: lean_delivery.zabbix_agent
      zabbix_agent_server: "test.zabbix.com"
      zabbix_agent_serveractive: "test.zabbix.com"
      zabbix_agent_hostmetadata: "test metadata"
