---
- name: Install nginx and copy config files
  hosts: all


  vars:
    source_site_1: ./default1
    source_site_2: ./default2
    source_config: ./nginx.conf
    destinationsite1: /etc/nginx/sites-available/default1
    destinationsite2: /etc/nginx/sites-available/default2
    destination_config: /etc/nginx/nginx.conf


  tasks:
  - name: Install nginx
    apt: name=nginx state=latest

  - name: Copy  nginx default config
    copy: src={{ source_config }} dest={{ destination_config }} mode=0777
    notify: nginx_reload


  - name: Copy  nginx config file for site 1
    copy: src={{ source_site_1 }} dest={{ destinationsite1 }} mode=0777


  - name: Create symlink for site1
    file: src={{ destinationsite1 }} dest=/etc/nginx/sites-enabled/default1 state=link
    notify: nginx_reload


  - name: Copy  nginx config file for site 2
    copy: src={{ source_site_2 }} dest={{ destinationsite2 }} mode=0777


  - name: Create symlink for site2
    file: src={{ destinationsite2 }} dest=/etc/nginx/sites-enabled/default2 state=link
    notify: nginx_reload

  handlers:
  - name: nginx_reload
    shell: /etc/init.d/nginx reload
