---
all:
  hosts:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/ansible_tasks
  children:
    lb:
      hosts:
        ag4544-lb.devops.rebrain.srwx.net:
    app:
     hosts:
        ag4544-app.devops.rebrain.srwx.net:
